Add redis-cluster and rabbitmq images
getsentry/image-mirror pull request #11
Opened 2023-06-07 14:13 UTC by beezz

2023-06-07 14:15 UTC, asottile-sentry requested changes

2023-06-07 14:15 UTC, asottile-sentry commented on main.py
> +        source='rabbitmq:',
this doesn't look right

2023-06-07 14:15 UTC, asottile-sentry commented on main.py
> +            'sha256:1e4b14cf748a9178a921d1cc784903eed586be700b04e49dc308a125babd8707',  # noqa: E501
without arm images these won't work in the development environment

2023-06-20 07:35 UTC, beezz commented on main.py
> +            'sha256:1e4b14cf748a9178a921d1cc784903eed586be700b04e49dc308a125babd8707',  # noqa: E501
changed that to images with arm that I built from the same repo

2023-06-26 13:33 UTC, asottile-sentry commented on main.py
> +            'sha256:c80c4d52e1f8bb8327dbee806894db94f2a2fbc31e9ecace5da1dce67ec8a5ad',  # noqa: E501
you'll want to `checkout -p` the unrelated changes

2023-06-26 13:34 UTC, asottile-sentry commented on main.py
> +        source='beezz/redis-cluster',
this should be a sentry repo if we're not going to use the upstream.  we can push directly to ghcr instead of using the image mirror for that

2023-06-26 21:15 UTC, asottile-sentry approved these changes
![](https://i.fluffy.cc/MKjDMmwXxZlqRTwnn070gVqZ8Rwh6d3p.gif)

2023-06-26 21:15 UTC, merged